version: '3'

services:

  archivy:
    build:
      context: .
      args: VERSION=0.11.1
    container_name: archivy
    ports:
      - 5000:5000
    environment:
      - FLASK_DEBUG=0
      - ELASTICSEARCH_ENABLED=1
      - ELASTICSEARCH_URL=http://elasticsearch:9200/
    volumes:
      - archivy_data:/archivy:rw
  elasticsearch:
    image: elasticsearch:7.9.0
    container_name: elasticsearch
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"

volumes:
  archivy_data:
  elasticsearch_data: